/*
Login form validation.
 */
export const USER_LOGIN_FIELD_ERROR   = 'USER_LOGIN_FIELD_ERROR';
export const USER_LOGIN_FIELD_NOERROR = 'USER_LOGIN_FIELD_NOERROR';
export const USER_PASS_FIELD_ERROR    = 'USER_PASS_FIELD_ERROR';
export const USER_PASS_FIELD_NOERROR  = 'USER_PASS_FIELD_NOERROR';

/*
Login.
 */
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGGED_IN     = 'USER_LOGGED_IN';
export const USER_LOGIN_FALSE   = 'USER_LOGIN_FALSE';
export const USER_LOGGED_OUT    = 'USER_LOGGED_OUT';

/*
Tree.
 */
export const GET_TREE_REQUEST = 'GET_TREE_REQUEST';
export const GET_TREE_DONE    = 'GET_TREE_DONE';
export const GET_TREE_FALSE   = 'GET_TREE_FALSE';
export const ADD_TREE_PAGE    = 'ADD_TREE_PAGE';

/*
Objects list.
 */
export const LIST_GET_DATA_REQUEST = 'LIST_GET_DATA_REQUEST';
export const LIST_GET_DATA_DONE    = 'LIST_GET_DATA_DONE';
export const LIST_GET_DATA_FALSE   = 'LIST_GET_DATA_FALSE';
export const LIST_UPDATE           = 'LIST_UPDATE';

/*
Edit form.
 */
export const EDIT_FORM_GET_DATA_REQUEST = 'EDIT_FORM_GET_DATA_REQUEST';
export const EDIT_FORM_GET_DATA_DONE    = 'EDIT_FORM_GET_DATA_DONE';
export const EDIT_FORM_GET_DATA_FALSE   = 'EDIT_FORM_GET_DATA_FALSE';
export const EDIT_FORM_FIELD_ERROR      = 'EDIT_FORM_FIELD_ERROR';
export const EDIT_FORM_FIELD_NO_ERROR   = 'EDIT_FORM_FIELD_NO_ERROR';
export const EDIT_FORM_SAVE_REQUEST     = 'EDIT_FORM_SAVE_REQUEST';
export const EDIT_FORM_SAVE_DONE        = 'EDIT_FORM_SAVE_DONE';
export const EDIT_FORM_SAVE_FALSE       = 'EDIT_FORM_SAVE_FALSE';
export const EDIT_FORM_UPDATE           = 'EDIT_FORM_UPDATE';
export const EDIT_FORM_DISMISS_ALERT    = 'EDIT_FORM_DISMISS_ALERT';
